# -*- coding: utf-8 -*-
"""Simulador_Macro_ISLM_AIFS2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPWma8Bq7viJk8vovgEkIf6nSIoksaNZ
"""

import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display

# ==========================================
# 1. LÓGICA DEL MODELO (MATRICIAL)
# ==========================================

def resolver_sistema(G, M, T, c1, I0, b, P, d1, d2):
    """
    Función auxiliar que resuelve un solo sistema matricial y devuelve los resultados.
    """
    # Definir Matriz A y Vector B
    A_autonomo = I0 + G - c1*T

    Matriz_A = np.array([
        [1-c1,  b],
        [d1,   -d2]
    ])

    Vector_B = np.array([
        A_autonomo,
        M/P
    ])

    det_A = np.linalg.det(Matriz_A)

    if abs(det_A) < 1e-9:
        return None, None, None, None # Error

    solucion = np.linalg.solve(Matriz_A, Vector_B)
    Y_eq, i_eq = solucion

    return Y_eq, i_eq, A_autonomo, Matriz_A # Retornamos datos necesarios

def graficar_comparativa(
    G_base, M_base, T_base,
    G_new, M_new, T_new,
    c1, I0, b, P, d1, d2
):
    # --- 1. RESOLVER ESCENARIO BASE ---
    Y1, i1, A1, _ = resolver_sistema(G_base, M_base, T_base, c1, I0, b, P, d1, d2)

    # --- 2. RESOLVER ESCENARIO NUEVO ---
    Y2, i2, A2, Matriz_A = resolver_sistema(G_new, M_new, T_new, c1, I0, b, P, d1, d2)

    if Y1 is None or Y2 is None:
        print("❌ Error: Determinante cercano a 0 en alguno de los escenarios.")
        return

    # --- 3. CONFIGURACIÓN DEL GRÁFICO ---

    # Calcular rango visual (basado en el mayor Y para que entren ambos)
    max_Y = max(Y1, Y2) * 1.5
    if max_Y < 100: max_Y = 1000
    Y_vals = np.arange(0, max_Y, 10)

    plt.figure(figsize=(10, 6))

    # --- GRAFICAR ESCENARIO BASE (PUNTEADO / GRIS) ---
    # IS Base
    i_IS_1 = (A1 - (1-c1)*Y_vals) / b
    # LM Base
    i_LM_1 = (1/d2) * (d1*Y_vals - M_base/P)

    plt.plot(Y_vals, i_IS_1, linestyle='--', color='lightblue', alpha=0.7, label='IS Inicial')
    plt.plot(Y_vals, i_LM_1, linestyle='--', color='salmon', alpha=0.7, label='LM Inicial')
    plt.plot(Y1, i1, 'o', color='gray', alpha=0.5, markersize=8) # Punto Eq 1

    # --- GRAFICAR ESCENARIO NUEVO (SÓLIDO / COLOR) ---
    # IS Nueva
    i_IS_2 = (A2 - (1-c1)*Y_vals) / b
    # LM Nueva
    i_LM_2 = (1/d2) * (d1*Y_vals - M_new/P)

    plt.plot(Y_vals, i_IS_2, color='blue', linewidth=2, label='IS Nueva')
    plt.plot(Y_vals, i_LM_2, color='red', linewidth=2, label='LM Nueva')
    plt.plot(Y2, i2, 'ko', markersize=10, label='Equilibrio Final') # Punto Eq 2

    # --- DECORACIÓN Y FLECHAS ---

    # Flecha de desplazamiento (del punto 1 al 2)
    plt.annotate('', xy=(Y2, i2), xytext=(Y1, i1),
                 arrowprops=dict(facecolor='black', shrink=0.05, width=1.5, headwidth=8))

    # Líneas guía al nuevo equilibrio
    plt.vlines(Y2, min(0, i2), i2, linestyles='dotted', colors='grey')
    plt.hlines(i2, 0, Y2, linestyles='dotted', colors='grey')

    # Títulos
    plt.title(f'Estática Comparativa IS-LM\nCambio: G({G_base}→{G_new}) | M({M_base}→{M_new})', fontsize=14)
    plt.xlabel('Producción (Y)')
    plt.ylabel('Tasa de Interés (i)')

    # Ajuste Ejes
    plt.xlim(0, max_Y)
    piso = min(0, i1, i2) - 0.05
    techo = max(0.2, i1, i2) + 0.10
    plt.ylim(piso, techo)
    plt.axhline(0, color='black', linewidth=1)

    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()

    # --- 4. TABLA DE RESULTADOS ---
    var_Y = Y2 - Y1
    var_i = (i2 - i1) * 100 # En puntos porcentuales

    print("-" * 60)
    print(f" 📊 ANÁLISIS DE IMPACTO (Δ)")
    print("-" * 60)
    print(f"{'Variable':<15} | {'Inicial (E1)':<15} | {'Final (E2)':<15} | {'Variación (Δ)':<15}")
    print("-" * 60)
    print(f"{'Producción (Y)':<15} | {Y1:<15.2f} | {Y2:<15.2f} | {var_Y:+15.2f}")
    print(f"{'Tasa (i)':<15} | {i1*100:<14.2f}% | {i2*100:<14.2f}% | {var_i:+14.2f} pp")
    print("-" * 60)
    print(f"Determinante del Sistema: {np.linalg.det(Matriz_A):.2f} (Estabilidad estructural constante)")


# ==========================================
# 2. INTERFAZ GRÁFICA (WIDGETS)
# ==========================================

style = {'description_width': 'initial'}
box_layout = widgets.Layout(width='95%')
col_layout = widgets.Layout(width='32%', border='1px solid #ddd', padding='5px', margin='2px') # 3 columnas

# --- A. PARÁMETROS ESTRUCTURALES (Comunes) ---
w_c1 = widgets.FloatText(value=0.6, step=0.05, description='c1', style=style, layout=box_layout)
w_I0 = widgets.FloatText(value=150, step=10, description='I0', style=style, layout=box_layout)
w_b  = widgets.FloatText(value=1000, step=50, description='b', style=style, layout=box_layout)
w_P  = widgets.FloatText(value=1, step=0.1, description='P', style=style, layout=box_layout)
w_d1 = widgets.FloatText(value=2, step=0.1, description='d1', style=style, layout=box_layout)
w_d2 = widgets.FloatText(value=1000, step=50, description='d2', style=style, layout=box_layout)

# --- B. ESCENARIO BASE (Inicial) ---
w_G1 = widgets.FloatText(value=300, step=10, description='Gasto (G1)', style=style, layout=box_layout)
w_M1 = widgets.FloatText(value=1600, step=50, description='Oferta M (M1)', style=style, layout=box_layout)
w_T1 = widgets.FloatText(value=100, step=10, description='Impuestos (T1)', style=style, layout=box_layout)

# --- C. ESCENARIO NUEVO (Shock) ---
w_G2 = widgets.FloatText(value=400, step=10, description='Gasto (G2)', style=style, layout=box_layout)
w_M2 = widgets.FloatText(value=1600, step=50, description='Oferta M (M2)', style=style, layout=box_layout)
w_T2 = widgets.FloatText(value=100, step=10, description='Impuestos (T2)', style=style, layout=box_layout)


# Botón de acción
btn_comparar = widgets.Button(
    description="🔄 SIMULAR CAMBIO DE POLÍTICA",
    button_style='success',
    layout=widgets.Layout(width='99%', height='50px', margin='10px 0px')
)

out_comparativa = widgets.Output()

def al_comparar(b):
    out_comparativa.clear_output(wait=True)
    with out_comparativa:
        graficar_comparativa(
            w_G1.value, w_M1.value, w_T1.value, # Base
            w_G2.value, w_M2.value, w_T2.value, # Nuevo
            w_c1.value, w_I0.value, w_b.value, w_P.value, w_d1.value, w_d2.value # Estructura
        )

btn_comparar.on_click(al_comparar)
al_comparar(None) # Ejecutar al inicio

# --- DISEÑO VISUAL ---
header_style = "text-align:center; background:#eee; padding:5px; margin-bottom:10px;"

col_struct = widgets.VBox([
    widgets.HTML(f"<div style='{header_style}'><b>1. Estructura Económica</b></div>"),
    w_c1, w_I0, w_b, w_P, w_d1, w_d2
], layout=col_layout)

col_base = widgets.VBox([
    widgets.HTML(f"<div style='{header_style}'><b>2. Escenario Inicial (Base)</b></div>"),
    w_G1, w_M1, w_T1,
    widgets.HTML("<small style='color:gray'>Estado original de la economía.</small>")
], layout=col_layout)

col_new = widgets.VBox([
    widgets.HTML(f"<div style='{header_style}'><b>3. Nuevo Escenario (Shock)</b></div>"),
    w_G2, w_M2, w_T2,
    widgets.HTML("<small style='color:blue'>Modifica esto para ver el cambio.</small>")
], layout=col_layout)

ui_final = widgets.VBox([
    widgets.HTML("<h2>⚖️ Simulador de Política Económica: Análisis Comparativo</h2>"),
    widgets.HBox([col_struct, col_base, col_new]),
    btn_comparar,
    out_comparativa
])

display(ui_final)